version: 2

submodules:
  include: all

sphinx:
  configuration: doc/conf.py

python:
  version: 3.7
  install:
  - requirements: ci/requirements.txt
  - method: pip
    path: .
    extra_requirements:
    - doc
    - hist
